const roles = [

    // Defenders
    {
        // label: "Außenverteidiger (Verteidigen)",
        id: "r1",
        attributes: {

            Fin: 0,
            Fir: 0,
            Mar: 2,
            Dri: 0,
            Cor: 0,
            Pen: 0,
            Cro: 1,
            Fre: 0,
            Hea: 0,
            Pas: 1,
            Tck: 2,
            Tec: 0,
            L_Th: 0,
            Lon: 0,
            Agg: 0,
            Ant: 2,
            WOR: 0,
            Dec: 1,
            Fla: 0,
            Ldr: 0,
            Cnt: 2,
            Bra: 0,
            Cmp: 1,
            OTB: 0,
            Pos: 2,
            Tea: 1,
            Vis: 0,
            Det: 0,

            Acc: 0,
            Sta: 1,
            Bal: 0,
            Agi: 0,
            Nat: 0,
            Str: 0,
            Pac: 1,
            Jum: 0,
        }
    },
    {
        // label: "Außenverteidiger (Unterstützen)",
        id: "r2",
        attributes: {

            Fin: 0,
            Fir: 0,
            Mar: 2,
            Dri: 1,
            Cor: 0,
            Pen: 0,
            Cro: 1,
            Fre: 0,
            Hea: 0,
            Pas: 1,
            Tck: 2,
            Tec: 1,
            L_Th: 0,
            Lon: 0,

            Agg: 0,
            Ant: 2,
            WOR: 2,
            Dec: 1,
            Fla: 0,
            Ldr: 0,
            Cnt: 2,
            Bra: 0,
            Cmp: 1,
            OTB: 0,
            Pos: 2,
            Tea: 2,
            Vis: 0,
            Det: 0,

            Acc: 0,
            Sta: 1,
            Bal: 0,
            Agi: 0,
            Nat: 0,
            Str: 0,
            Pac: 1,
            Jum: 0,
        }
    },
    {
        // label: "Außenverteidiger (Angreifen)",
        id: "r3",
        attributes: {

            Fin: 0,
            Fir: 1,
            Mar: 1,
            Dri: 1,
            Cor: 0,
            Pen: 0,
            Cro: 2,
            Fre: 0,
            Hea: 0,
            Pas: 1,
            Tck: 2,
            Tec: 1,
            L_Th: 0,
            Lon: 0,

            Agg: 0,
            Ant: 2,
            WOR: 2,
            Dec: 1,
            Fla: 0,
            Ldr: 0,
            Cnt: 1,
            Bra: 0,
            Cmp: 1,
            OTB: 1,
            Pos: 2,
            Tea: 2,
            Vis: 0,
            Det: 0,

            Acc: 1,
            Sta: 2,
            Bal: 0,
            Agi: 1,
            Nat: 0,
            Str: 0,
            Pac: 2,
            Jum: 0,
        }
    },
    {
        // label: "Ballspielender Verteidiger (Verteidigen)",
        id: "r4",
        attributes: {

            Fin: 0,
            Fir: 1,
            Mar: 2,
            Dri: 0,
            Cor: 0,
            Pen: 0,
            Cro: 0,
            Fre: 0,
            Hea: 2,
            Pas: 2,
            Tck: 2,
            Tec: 1,
            L_Th: 0,
            Lon: 0,

            Agg: 1,
            Ant: 1,
            WOR: 0,
            Dec: 1,
            Fla: 0,
            Ldr: 0,
            Cnt: 1,
            Bra: 1,
            Cmp: 2,
            OTB: 0,
            Pos: 2,
            Tea: 0,
            Vis: 1,
            Det: 0,

            Acc: 0,
            Sta: 0,
            Bal: 0,
            Agi: 0,
            Nat: 0,
            Str: 2,
            Pac: 1,
            Jum: 2,
        }
    },
    {
        // label: "Ballspielender Verteidiger (Vorstopper)",
        id: "r5",
        attributes: {

            Fin: 0,
            Fir: 1,
            Mar: 1,
            Dri: 0,
            Cor: 0,
            Pen: 0,
            Cro: 0,
            Fre: 0,
            Hea: 2,
            Pas: 2,
            Tck: 2,
            Tec: 1,
            L_Th: 0,
            Lon: 0,

            Agg: 2,
            Ant: 1,
            WOR: 0,
            Dec: 2,
            Fla: 0,
            Ldr: 0,
            Cnt: 1,
            Bra: 2,
            Cmp: 2,
            OTB: 0,
            Pos: 2,
            Tea: 0,
            Vis: 1,
            Det: 0,

            Acc: 0,
            Sta: 0,
            Bal: 0,
            Agi: 0,
            Nat: 0,
            Str: 2,
            Pac: 0,
            Jum: 2,
        }
    },

    {
        // label: "Ballspielender Verteidiger (Rückendeckend)",
        id: "r6",
        attributes: {

            Fin: 0,
            Fir: 1,
            Mar: 2,
            Dri: 0,
            Cor: 0,
            Pen: 0,
            Cro: 0,
            Fre: 0,
            Hea: 1,
            Pas: 2,
            Tck: 2,
            Tec: 1,
            L_Th: 0,
            Lon: 0,

            Agg: 0,
            Ant: 2,
            WOR: 0,
            Dec: 2,
            Fla: 0,
            Ldr: 0,
            Cnt: 2,
            Bra: 1,
            Cmp: 2,
            OTB: 0,
            Pos: 2,
            Tea: 0,
            Vis: 1,
            Det: 0,

            Acc: 0,
            Sta: 0,
            Bal: 0,
            Agi: 0,
            Nat: 0,
            Str: 1,
            Pac: 2,
            Jum: 1,
        }
    },
    {
        // label: "Flügelverteidiger (Verteidigen)",
        id: "r7",
        attributes: {

            Fin: 0,
            Fir: 1,
            Mar: 2,
            Dri: 1,
            Cor: 0,
            Pen: 0,
            Cro: 1,
            Fre: 0,
            Hea: 0,
            Pas: 1,
            Tck: 2,
            Tec: 1,
            L_Th: 0,
            Lon: 0,

            Agg: 0,
            Ant: 2,
            WOR: 2,
            Dec: 1,
            Fla: 0,
            Ldr: 0,
            Cnt: 1,
            Bra: 0,
            Cmp: 0,
            OTB: 1,
            Pos: 2,
            Tea: 2,
            Vis: 0,
            Det: 0,

            Acc: 2,
            Sta: 2,
            Bal: 0,
            Agi: 1,
            Nat: 0,
            Str: 0,
            Pac: 1,
            Jum: 0,
        }
    },
    {
        // label: "Flügelverteidiger (Unterstützend)",
        id: "r8",
        attributes: {

            Fin: 0,
            Fir: 1,
            Mar: 2,
            Dri: 2,
            Cor: 0,
            Pen: 0,
            Cro: 2,
            Fre: 0,
            Hea: 0,
            Pas: 1,
            Tck: 2,
            Tec: 1,
            L_Th: 0,
            Lon: 0,

            Agg: 0,
            Ant: 1,
            WOR: 2,
            Dec: 1,
            Fla: 0,
            Ldr: 0,
            Cnt: 1,
            Bra: 0,
            Cmp: 0,
            OTB: 2,
            Pos: 1,
            Tea: 2,
            Vis: 0,
            Det: 0,

            Acc: 2,
            Sta: 2,
            Bal: 0,
            Agi: 1,
            Nat: 0,
            Str: 0,
            Pac: 1,
            Jum: 0,
        }
    },
    {
        // label: "Flügelverteidiger (Angreifend)",
        id: "r9",
        attributes: {

            Fin: 0,
            Fir: 1,
            Mar: 1,
            Dri: 2,
            Cor: 0,
            Pen: 0,
            Cro: 2,
            Fre: 0,
            Hea: 0,
            Pas: 1,
            Tck: 2,
            Tec: 2,
            L_Th: 0,
            Lon: 0,
            Agg: 0,
            Ant: 1,
            WOR: 2,
            Dec: 1,
            Fla: 1,
            Ldr: 0,
            Cnt: 1,
            Bra: 0,
            Cmp: 0,
            OTB: 2,
            Pos: 1,
            Tea: 2,
            Vis: 0,
            Det: 0,

            Acc: 2,
            Sta: 2,
            Bal: 0,
            Agi: 1,
            Nat: 0,
            Str: 0,
            Pac: 2,
            Jum: 0,
        }
    },
    {
        // label: "Innenverteidiger (Verteidigen)",
        id: "r10",
        attributes: {

            Fin: 0,
            Fir: 0,
            Mar: 2,
            Dri: 0,
            Cor: 0,
            Pen: 0,
            Cro: 0,
            Fre: 0,
            Hea: 2,
            Pas: 0,
            Tck: 2,
            Tec: 0,
            L_Th: 0,
            Lon: 0,

            Agg: 1,
            Ant: 1,
            WOR: 0,
            Dec: 1,
            Fla: 0,
            Ldr: 0,
            Cnt: 1,
            Bra: 1,
            Cmp: 1,
            OTB: 0,
            Pos: 2,
            Tea: 0,
            Vis: 0,
            Det: 0,

            Acc: 0,
            Sta: 0,
            Bal: 0,
            Agi: 0,
            Nat: 0,
            Str: 2,
            Pac: 1,
            Jum: 2,
        }
    },
    {
        // label: "Innenverteidiger (Vorstopper)",
        id: "r11",
        attributes: {

            Fin: 0,
            Fir: 0,
            Mar: 1,
            Dri: 0,
            Cor: 0,
            Pen: 0,
            Cro: 0,
            Fre: 0,
            Hea: 2,
            Pas: 0,
            Tck: 2,
            Tec: 0,
            L_Th: 0,
            Lon: 0,

            Agg: 2,
            Ant: 1,
            WOR: 0,
            Dec: 2,
            Fla: 0,
            Ldr: 0,
            Cnt: 1,
            Bra: 2,
            Cmp: 1,
            OTB: 0,
            Pos: 2,
            Tea: 0,
            Vis: 0,
            Det: 0,

            Acc: 0,
            Sta: 0,
            Bal: 0,
            Agi: 0,
            Nat: 0,
            Str: 2,
            Pac: 0,
            Jum: 2,
        }
    },
    {
        // label: "Innenverteidiger (Rückendecken)",
        id: "r12",
        attributes: {

            Fin: 0,
            Fir: 0,
            Mar: 2,
            Dri: 0,
            Cor: 0,
            Pen: 0,
            Cro: 0,
            Fre: 0,
            Hea: 1,
            Pas: 0,
            Tck: 2,
            Tec: 0,
            L_Th: 0,
            Lon: 0,

            Agg: 0,
            Ant: 2,
            WOR: 0,
            Dec: 2,
            Fla: 0,
            Ldr: 0,
            Cnt: 2,
            Bra: 1,
            Cmp: 1,
            OTB: 0,
            Pos: 2,
            Tea: 0,
            Vis: 0,
            Det: 0,

            Acc: 0,
            Sta: 0,
            Bal: 0,
            Agi: 0,
            Nat: 0,
            Str: 1,
            Pac: 2,
            Jum: 1,
        }
    },
    {
        // label: "Inverser Außenverteidiger (Verteidigen)",
        id: "r13",
        attributes: {

            Fin: 0,
            Fir: 1,
            Mar: 2,
            Dri: 1,
            Cor: 0,
            Pen: 0,
            Cro: 0,
            Fre: 0,
            Hea: 0,
            Pas: 2,
            Tck: 2,
            Tec: 1,
            L_Th: 0,
            Lon: 0,

            Agg: 0,
            Ant: 2,
            WOR: 2,
            Dec: 2,
            Fla: 0,
            Ldr: 0,
            Cnt: 1,
            Bra: 0,
            Cmp: 0,
            OTB: 1,
            Pos: 2,
            Tea: 2,
            Vis: 0,
            Det: 0,

            Acc: 1,
            Sta: 1,
            Bal: 0,
            Agi: 1,
            Nat: 0,
            Str: 0,
            Pac: 0,
            Jum: 0,
        }
    },
    {
        // label: "Inverser Außenverteidiger (Unterstützen)",
        id: "r14",
        attributes: {

            Fin: 0,
            Fir: 1,
            Mar: 2,
            Dri: 1,
            Cor: 0,
            Pen: 0,
            Cro: 0,
            Fre: 0,
            Hea: 0,
            Pas: 2,
            Tck: 2,
            Tec: 1,
            L_Th: 0,
            Lon: 0,

            Agg: 0,
            Ant: 1,
            WOR: 2,
            Dec: 2,
            Fla: 0,
            Ldr: 0,
            Cnt: 1,
            Bra: 0,
            Cmp: 1,
            OTB: 2,
            Pos: 1,
            Tea: 2,
            Vis: 0,
            Det: 0,

            Acc: 1,
            Sta: 2,
            Bal: 0,
            Agi: 1,
            Nat: 0,
            Str: 0,
            Pac: 0,
            Jum: 0,
        }
    },
    {
        // label: "Inverser Außenverteidiger (Angreifen)",
        id: "r15",
        attributes: {

            Fin: 0,
            Fir: 1,
            Mar: 2,
            Dri: 1,
            Cor: 0,
            Pen: 0,
            Cro: 0,
            Fre: 0,
            Hea: 0,
            Pas: 2,
            Tck: 2,
            Tec: 2,
            L_Th: 0,
            Lon: 1,

            Agg: 0,
            Ant: 1,
            WOR: 2,
            Dec: 2,
            Fla: 1,
            Ldr: 0,
            Cnt: 1,
            Bra: 0,
            Cmp: 1,
            OTB: 2,
            Pos: 1,
            Tea: 2,
            Vis: 0,
            Det: 0,

            Acc: 2,
            Sta: 2,
            Bal: 0,
            Agi: 1,
            Nat: 0,
            Str: 0,
            Pac: 1,
            Jum: 0,
        }
    },
    {
        // label: "Kompletter Flügelverteidiger (Unterstützend)",
        id: "r16",
        attributes: {

            Fin: 0,
            Fir: 2,
            Mar: 0,
            Dri: 2,
            Cor: 0,
            Pen: 0,
            Cro: 2,
            Fre: 0,
            Hea: 0,
            Pas: 2,
            Tck: 1,
            Tec: 2,
            L_Th: 0,
            Lon: 0,

            Agg: 0,
            Ant: 1,
            WOR: 2,
            Dec: 2,
            Fla: 1,
            Ldr: 0,
            Cnt: 0,
            Bra: 0,
            Cmp: 1,
            OTB: 2,
            Pos: 0,
            Tea: 2,
            Vis: 0,
            Det: 0,

            Acc: 2,
            Sta: 2,
            Bal: 1,
            Agi: 1,
            Nat: 0,
            Str: 0,
            Pac: 2,
            Jum: 0,
        }
    },
    {
        // label: "Kompletter Flügelverteidiger (Angreifen)",
        id: "r17",
        attributes: {

            Fin: 0,
            Fir: 2,
            Mar: 0,
            Dri: 2,
            Cor: 0,
            Pen: 0,
            Cro: 2,
            Fre: 0,
            Hea: 0,
            Pas: 2,
            Tck: 1,
            Tec: 2,
            L_Th: 0,
            Lon: 0,

            Agg: 0,
            Ant: 1,
            WOR: 2,
            Dec: 2,
            Fla: 2,
            Ldr: 0,
            Cnt: 0,
            Bra: 0,
            Cmp: 1,
            OTB: 2,
            Pos: 0,
            Tea: 2,
            Vis: 0,
            Det: 0,

            Acc: 2,
            Sta: 2,
            Bal: 1,
            Agi: 1,
            Nat: 0,
            Str: 0,
            Pac: 2,
            Jum: 0,
        }
    },
    {
        // label: "Kompromissloser Außenverteidiger (Verteidigen)",
        id: "r18",
        attributes: {

            Fin: 0,
            Fir: 0,
            Mar: 2,
            Dri: 0,
            Cor: 0,
            Pen: 0,
            Cro: 0,
            Fre: 0,
            Hea: 1,
            Pas: 0,
            Tck: 0,
            Tec: 2,
            L_Th: 0,
            Lon: 0,

            Agg: 1,
            Ant: 2,
            WOR: 0,
            Dec: 0,
            Fla: 0,
            Ldr: 0,
            Cnt: 1,
            Bra: 1,
            Cmp: 0,
            OTB: 0,
            Pos: 2,
            Tea: 1,
            Vis: 0,
            Det: 0,

            Acc: 0,
            Sta: 0,
            Bal: 0,
            Agi: 0,
            Nat: 0,
            Str: 2,
            Pac: 0,
            Jum: 0,
        }
    },
    {
        // label: "Kompromissloser Innenverteidiger (Verteidigen)",
        id: "r19",
        attributes: {

            Fin: 0,
            Fir: 0,
            Mar: 2,
            Dri: 0,
            Cor: 0,
            Pen: 0,
            Cro: 0,
            Fre: 0,
            Hea: 2,
            Pas: 0,
            Tck: 2,
            Tec: 0,
            L_Th: 0,
            Lon: 0,

            Agg: 1,
            Ant: 1,
            WOR: 0,
            Dec: 0,
            Fla: 0,
            Ldr: 0,
            Cnt: 1,
            Bra: 1,
            Cmp: 0,
            OTB: 0,
            Pos: 2,
            Tea: 0,
            Vis: 0,
            Det: 0,

            Acc: 0,
            Sta: 0,
            Bal: 0,
            Agi: 0,
            Nat: 0,
            Str: 2,
            Pac: 1,
            Jum: 2,
        }
    },
    {
        // label: "Kompromissloser Innenverteidiger (Vorstopper)",
        id: "r20",
        attributes: {

            Fin: 0,
            Fir: 0,
            Mar: 1,
            Dri: 0,
            Cor: 0,
            Pen: 0,
            Cro: 0,
            Fre: 0,
            Hea: 2,
            Pas: 0,
            Tck: 2,
            Tec: 0,
            L_Th: 0,
            Lon: 0,

            Agg: 2,
            Ant: 1,
            WOR: 0,
            Dec: 0,
            Fla: 0,
            Ldr: 0,
            Cnt: 1,
            Bra: 2,
            Cmp: 0,
            OTB: 0,
            Pos: 2,
            Tea: 0,
            Vis: 0,
            Det: 0,

            Acc: 0,
            Sta: 0,
            Bal: 0,
            Agi: 0,
            Nat: 0,
            Str: 2,
            Pac: 0,
            Jum: 2,
        }
    },
    {
        // label: "Kompromissloser Innenverteidiger (Rückendeckung)",
        id: "r21",
        attributes: {

            Fin: 0,
            Fir: 0,
            Mar: 2,
            Dri: 0,
            Cor: 0,
            Pen: 0,
            Cro: 0,
            Fre: 0,
            Hea: 1,
            Pas: 0,
            Tck: 2,
            Tec: 0,
            L_Th: 0,
            Lon: 0,

            Agg: 0,
            Ant: 2,
            WOR: 0,
            Dec: 0,
            Fla: 0,
            Ldr: 0,
            Cnt: 2,
            Bra: 1,
            Cmp: 0,
            OTB: 0,
            Pos: 2,
            Tea: 0,
            Vis: 0,
            Det: 0,

            Acc: 0,
            Sta: 0,
            Bal: 0,
            Agi: 0,
            Nat: 0,
            Str: 1,
            Pac: 2,
            Jum: 1,
        }
    },
    {
        // label: "Libero (Unterstützend)",
        id: "r22",
        attributes: {

            Fin: 0,
            Fir: 2,
            Mar: 2,
            Dri: 1,
            Cor: 0,
            Pen: 0,
            Cro: 0,
            Fre: 0,
            Hea: 1,
            Pas: 2,
            Tck: 2,
            Tec: 1,
            L_Th: 0,
            Lon: 0,

            Agg: 0,
            Ant: 2,
            WOR: 0,
            Dec: 2,
            Fla: 1,
            Ldr: 0,
            Cnt: 2,
            Bra: 1,
            Cmp: 2,
            OTB: 0,
            Pos: 2,
            Tea: 2,
            Vis: 2,
            Det: 0,

            Acc: 0,
            Sta: 1,
            Bal: 1,
            Agi: 1,
            Nat: 0,
            Str: 1,
            Pac: 2,
            Jum: 1,
        }
    },
    {
        // label: "Libero (Angreifen)",
        id: "r23",
        attributes: {

            Fin: 0,
            Fir: 2,
            Mar: 2,
            Dri: 2,
            Cor: 0,
            Pen: 0,
            Cro: 0,
            Fre: 0,
            Hea: 1,
            Pas: 2,
            Tck: 2,
            Tec: 1,
            L_Th: 0,
            Lon: 1,

            Agg: 0,
            Ant: 2,
            WOR: 0,
            Dec: 2,
            Fla: 2,
            Ldr: 0,
            Cnt: 2,
            Bra: 1,
            Cmp: 2,
            OTB: 0,
            Pos: 2,
            Tea: 2,
            Vis: 2,
            Det: 0,

            Acc: 1,
            Sta: 1,
            Bal: 1,
            Agi: 1,
            Nat: 0,
            Str: 1,
            Pac: 2,
            Jum: 1,
        }
    },

    // Midfield:
    {
        // label: "Abräumer (Verteidigen)",
        id: "r24",
        attributes: {

            Fin: 0,
            Fir: 0,
            Mar: 2,
            Dri: 0,
            Cor: 0,
            Pen: 0,
            Cro: 0,
            Fre: 0,
            Hea: 0,
            Pas: 0,
            Tck: 2,
            Tec: 0,
            L_Th: 0,
            Lon: 0,

            Agg: 0,
            Ant: 2,
            WOR: 0,
            Dec: 2,
            Fla: 0,
            Ldr: 0,
            Cnt: 2,
            Bra: 0,
            Cmp: 1,
            OTB: 0,
            Pos: 2,
            Tea: 1,
            Vis: 0,
            Det: 0,

            Acc: 0,
            Sta: 0,
            Bal: 0,
            Agi: 0,
            Nat: 0,
            Str: 1,
            Pac: 0,
            Jum: 0,
        }
    },
    {
        // label: "Äuserer Mittelfeldspieler (Verteidigen)",
        id: "r25",
        attributes: {

            Fin: 0,
            Fir: 1,
            Mar: 1,
            Dri: 0,
            Cor: 0,
            Pen: 0,
            Cro: 1,
            Fre: 0,
            Hea: 0,
            Pas: 2,
            Tck: 2,
            Tec: 1,
            L_Th: 0,
            Lon: 0,

            Agg: 0,
            Ant: 1,
            WOR: 2,
            Dec: 2,
            Fla: 0,
            Ldr: 0,
            Cnt: 2,
            Bra: 0,
            Cmp: 1,
            OTB: 0,
            Pos: 2,
            Tea: 2,
            Vis: 0,
            Det: 0,

            Acc: 0,
            Sta: 1,
            Bal: 0,
            Agi: 0,
            Nat: 0,
            Str: 0,
            Pac: 0,
            Jum: 0,
        }
    },
    {
        // label: "Äuserer Mittelfeldspieler (Unterstützen)",
        id: "r26",
        attributes: {

            Fin: 0,
            Fir: 1,
            Mar: 0,
            Dri: 0,
            Cor: 0,
            Pen: 0,
            Cro: 1,
            Fre: 0,
            Hea: 0,
            Pas: 2,
            Tck: 2,
            Tec: 1,
            L_Th: 0,
            Lon: 0,

            Agg: 0,
            Ant: 1,
            WOR: 2,
            Dec: 2,
            Fla: 0,
            Ldr: 0,
            Cnt: 1,
            Bra: 0,
            Cmp: 1,
            OTB: 1,
            Pos: 1,
            Tea: 2,
            Vis: 1,
            Det: 0,

            Acc: 0,
            Sta: 2,
            Bal: 0,
            Agi: 0,
            Nat: 0,
            Str: 0,
            Pac: 0,
            Jum: 0,
        }
    },
    {
        // label: "Äuserer Mittelfeldspieler (Angreifen)",
        id: "r27",
        attributes: {

            Fin: 0,
            Fir: 2,
            Mar: 0,
            Dri: 0,
            Cor: 0,
            Pen: 0,
            Cro: 2,
            Fre: 0,
            Hea: 0,
            Pas: 2,
            Tck: 1,
            Tec: 1,
            L_Th: 0,
            Lon: 0,

            Agg: 0,
            Ant: 1,
            WOR: 2,
            Dec: 2,
            Fla: 0,
            Ldr: 0,
            Cnt: 0,
            Bra: 0,
            Cmp: 1,
            OTB: 1,
            Pos: 0,
            Tea: 2,
            Vis: 1,
            Det: 0,

            Acc: 0,
            Sta: 2,
            Bal: 0,
            Agi: 0,
            Nat: 0,
            Str: 0,
            Pac: 0,
            Jum: 0,
        }
    },
    {
        // label: "Äußerer Spielmacher (Unterstützen)",
        id: "r28",
        attributes: {

            Fin: 0,
            Fir: 2,
            Mar: 0,
            Dri: 1,
            Cor: 0,
            Pen: 0,
            Cro: 0,
            Fre: 0,
            Hea: 0,
            Pas: 2,
            Tck: 0,
            Tec: 2,
            L_Th: 0,
            Lon: 0,

            Agg: 0,
            Ant: 0,
            WOR: 0,
            Dec: 2,
            Fla: 0,
            Ldr: 0,
            Cnt: 0,
            Bra: 0,
            Cmp: 2,
            OTB: 1,
            Pos: 0,
            Tea: 2,
            Vis: 2,
            Det: 0,

            Acc: 0,
            Sta: 0,
            Bal: 0,
            Agi: 1,
            Nat: 0,
            Str: 0,
            Pac: 0,
            Jum: 0,
        }
    },
    {
        // label: "Äußerer Spielmacher (Angreifen)",
        id: "r29",
        attributes: {

            Fin: 0,
            Fir: 2,
            Mar: 0,
            Dri: 2,
            Cor: 0,
            Pen: 0,
            Cro: 0,
            Fre: 0,
            Hea: 0,
            Pas: 2,
            Tck: 0,
            Tec: 2,
            L_Th: 0,
            Lon: 0,

            Agg: 0,
            Ant: 1,
            WOR: 0,
            Dec: 2,
            Fla: 1,
            Ldr: 0,
            Cnt: 0,
            Bra: 0,
            Cmp: 2,
            OTB: 2,
            Pos: 0,
            Tea: 2,
            Vis: 2,
            Det: 0,

            Acc: 1,
            Sta: 0,
            Bal: 0,
            Agi: 1,
            Nat: 0,
            Str: 0,
            Pac: 0,
            Jum: 0,
        }
    },
    {
        // label: "Äußerer Zielspieler (Unterstützen)",
        id: "r30",
        attributes: {

            Fin: 0,
            Fir: 1,
            Mar: 0,
            Dri: 0,
            Cor: 0,
            Pen: 0,
            Cro: 1,
            Fre: 0,
            Hea: 2,
            Pas: 0,
            Tck: 0,
            Tec: 0,
            L_Th: 0,
            Lon: 0,

            Agg: 0,
            Ant: 1,
            WOR: 1,
            Dec: 0,
            Fla: 0,
            Ldr: 0,
            Cnt: 0,
            Bra: 2,
            Cmp: 0,
            OTB: 1,
            Pos: 0,
            Tea: 2,
            Vis: 0,
            Det: 0,

            Acc: 0,
            Sta: 1,
            Bal: 1,
            Agi: 0,
            Nat: 0,
            Str: 2,
            Pac: 0,
            Jum: 2,
        }
    },
    {
        // label: "Äußerer Zielspieler (Angreifen)",
        id: "r31",
        attributes: {
            Fin: 1,
            Fir: 1,
            Mar: 0,
            Dri: 0,
            Cor: 0,
            Pen: 0,
            Cro: 1,
            Fre: 0,
            Hea: 2,
            Pas: 0,
            Tck: 0,
            Tec: 0,
            L_Th: 0,
            Lon: 0,

            Agg: 0,
            Ant: 1,
            WOR: 1,
            Dec: 0,
            Fla: 0,
            Ldr: 0,
            Cnt: 0,
            Bra: 2,
            Cmp: 0,
            OTB: 2,
            Pos: 0,
            Tea: 1,
            Vis: 0,
            Det: 0,

            Acc: 0,
            Sta: 1,
            Bal: 1,
            Agi: 0,
            Nat: 0,
            Str: 2,
            Pac: 0,
            Jum: 2,
        }
    },
    {
        // label: "Ballerobernder Mittelfeldspieler (Verteidigen)",
        id: "r32",
        attributes: {

            Fin: 0,
            Fir: 0,
            Mar: 1,
            Dri: 0,
            Cor: 0,
            Pen: 0,
            Cro: 0,
            Fre: 0,
            Hea: 0,
            Pas: 0,
            Tck: 2,
            Tec: 0,
            L_Th: 0,
            Lon: 0,

            Agg: 2,
            Ant: 2,
            WOR: 2,
            Dec: 0,
            Fla: 0,
            Ldr: 0,
            Cnt: 1,
            Bra: 2,
            Cmp: 0,
            OTB: 0,
            Pos: 1,
            Tea: 2,
            Vis: 0,
            Det: 0,

            Acc: 0,
            Sta: 1,
            Bal: 0,
            Agi: 1,
            Nat: 0,
            Str: 1,
            Pac: 1,
            Jum: 0,
        }
    },
    {
        // label: "Ballerobernder Mittelfeldspieler (Unterstützen)",
        id: "r33",
        attributes: {

            Fin: 0,
            Fir: 0,
            Mar: 1,
            Dri: 0,
            Cor: 0,
            Pen: 0,
            Cro: 0,
            Fre: 0,
            Hea: 0,
            Pas: 1,
            Tck: 2,
            Tec: 0,
            L_Th: 0,
            Lon: 0,

            Agg: 2,
            Ant: 2,
            WOR: 2,
            Dec: 0,
            Fla: 0,
            Ldr: 0,
            Cnt: 1,
            Bra: 2,
            Cmp: 0,
            OTB: 0,
            Pos: 0,
            Tea: 2,
            Vis: 0,
            Det: 0,

            Acc: 0,
            Sta: 1,
            Bal: 0,
            Agi: 1,
            Nat: 0,
            Str: 1,
            Pac: 1,
            Jum: 0,
        }
    },
    {
        // label: "Box-to-Box Mittelfeldspieler (Unterstützen)",
        id: "r34",
        attributes: {

            Fin: 1,
            Fir: 1,
            Mar: 0,
            Dri: 1,
            Cor: 0,
            Pen: 0,
            Cro: 0,
            Fre: 0,
            Hea: 0,
            Pas: 2,
            Tck: 2,
            Tec: 1,
            L_Th: 0,
            Lon: 1,

            Agg: 1,
            Ant: 1,
            WOR: 2,
            Dec: 1,
            Fla: 0,
            Ldr: 0,
            Cnt: 0,
            Bra: 0,
            Cmp: 1,
            OTB: 2,
            Pos: 1,
            Tea: 2,
            Vis: 0,
            Det: 0,

            Acc: 1,
            Sta: 2,
            Bal: 1,
            Agi: 0,
            Nat: 0,
            Str: 1,
            Pac: 1,
            Jum: 0,
        }
    },
    {
        // label: "Carrilero (Unterstützen)",
        id: "r35",
        attributes: {

            Fin: 0,
            Fir: 1,
            Mar: 0,
            Dri: 0,
            Cor: 0,
            Pen: 0,
            Cro: 0,
            Fre: 0,
            Hea: 0,
            Pas: 2,
            Tck: 2,
            Tec: 1,
            L_Th: 0,
            Lon: 0,

            Agg: 0,
            Ant: 1,
            WOR: 2,
            Dec: 2,
            Fla: 0,
            Ldr: 0,
            Cnt: 1,
            Bra: 0,
            Cmp: 1,
            OTB: 1,
            Pos: 2,
            Tea: 2,
            Vis: 1,
            Det: 0,

            Acc: 0,
            Sta: 2,
            Bal: 0,
            Agi: 0,
            Nat: 0,
            Str: 0,
            Pac: 0,
            Jum: 0,
        }
    },
    {
        // label: "Defensiver Flügelspieler (Verteidigen)",
        id: "r36",
        attributes: {

            Fin: 0,
            Fir: 1,
            Mar: 1,
            Dri: 1,
            Cor: 0,
            Pen: 0,
            Cro: 1,
            Fre: 0,
            Hea: 0,
            Pas: 0,
            Tck: 1,
            Tec: 2,
            L_Th: 0,
            Lon: 0,

            Agg: 1,
            Ant: 2,
            WOR: 2,
            Dec: 1,
            Fla: 0,
            Ldr: 0,
            Cnt: 1,
            Bra: 0,
            Cmp: 0,
            OTB: 2,
            Pos: 2,
            Tea: 2,
            Vis: 0,
            Det: 0,

            Acc: 1,
            Sta: 2,
            Bal: 0,
            Agi: 0,
            Nat: 0,
            Str: 0,
            Pac: 0,
            Jum: 0,
        }
    },
    {
        // label: "Defensiver Flügelspieler (Unterstützen)",
        id: "r37",
        attributes: {

            Fin: 0,
            Fir: 1,
            Mar: 1,
            Dri: 1,
            Cor: 0,
            Pen: 0,
            Cro: 2,
            Fre: 0,
            Hea: 0,
            Pas: 1,
            Tck: 1,
            Tec: 2,
            L_Th: 0,
            Lon: 0,

            Agg: 1,
            Ant: 1,
            WOR: 2,
            Dec: 1,
            Fla: 0,
            Ldr: 0,
            Cnt: 1,
            Bra: 0,
            Cmp: 1,
            OTB: 2,
            Pos: 1,
            Tea: 2,
            Vis: 0,
            Det: 0,

            Acc: 1,
            Sta: 2,
            Bal: 0,
            Agi: 0,
            Nat: 0,
            Str: 0,
            Pac: 0,
            Jum: 0,
        }
    },
    {
        // label: "Enganche (Unterstützen)",
        id: "r38",
        attributes: {

            Fin: 0,
            Fir: 2,
            Mar: 0,
            Dri: 0,
            Cor: 0,
            Pen: 0,
            Cro: 0,
            Fre: 0,
            Hea: 0,
            Pas: 2,
            Tck: 0,
            Tec: 2,
            L_Th: 0,
            Lon: 0,

            Agg: 0,
            Ant: 1,
            WOR: 0,
            Dec: 2,
            Fla: 1,
            Ldr: 0,
            Cnt: 0,
            Bra: 0,
            Cmp: 2,
            OTB: 1,
            Pos: 0,
            Tea: 0,
            Vis: 2,
            Det: 0,

            Acc: 0,
            Sta: 0,
            Bal: 1,
            Agi: 0,
            Nat: 0,
            Str: 0,
            Pac: 0,
            Jum: 0,
        }
    },
    {
        // label: "Flügelspieler (Unterstützen)",
        id: "r39",
        attributes: {

            Fin: 0,
            Fir: 1,
            Mar: 0,
            Dri: 2,
            Cor: 0,
            Pen: 0,
            Cro: 2,
            Fre: 0,
            Hea: 0,
            Pas: 1,
            Tck: 0,
            Tec: 2,
            L_Th: 0,
            Lon: 0,

            Agg: 0,
            Ant: 0,
            WOR: 1,
            Dec: 0,
            Fla: 0,
            Ldr: 0,
            Cnt: 0,
            Bra: 0,
            Cmp: 0,
            OTB: 2,
            Pos: 0,
            Tea: 0,
            Vis: 0,
            Det: 0,

            Acc: 2,
            Sta: 1,
            Bal: 0,
            Agi: 1,
            Nat: 0,
            Str: 0,
            Pac: 2,
            Jum: 0,
        }
    },
    {
        // label: "Flügelspieler (Angreifen)",
        id: "r40",
        attributes: {

            Fin: 0,
            Fir: 1,
            Mar: 0,
            Dri: 2,
            Cor: 0,
            Pen: 0,
            Cro: 2,
            Fre: 0,
            Hea: 0,
            Pas: 1,
            Tck: 0,
            Tec: 2,
            L_Th: 0,
            Lon: 0,

            Agg: 0,
            Ant: 0,
            WOR: 1,
            Dec: 0,
            Fla: 1,
            Ldr: 0,
            Cnt: 0,
            Bra: 0,
            Cmp: 0,
            OTB: 2,
            Pos: 0,
            Tea: 0,
            Vis: 0,
            Det: 0,

            Acc: 2,
            Sta: 0,
            Bal: 0,
            Agi: 1,
            Nat: 0,
            Str: 0,
            Pac: 2,
            Jum: 0,
        }
    },
    {
        // label: "Inverser Außenstürmer (Unterstützen)",
        id: "r41",
        attributes: {

            Fin: 1,
            Fir: 2,
            Mar: 0,
            Dri: 2,
            Cor: 0,
            Pen: 0,
            Cro: 0,
            Fre: 0,
            Hea: 0,
            Pas: 2,
            Tck: 0,
            Tec: 2,
            L_Th: 0,
            Lon: 1,

            Agg: 0,
            Ant: 1,
            WOR: 0,
            Dec: 0,
            Fla: 1,
            Ldr: 0,
            Cnt: 0,
            Bra: 0,
            Cmp: 1,
            OTB: 2,
            Pos: 0,
            Tea: 0,
            Vis: 1,
            Det: 0,

            Acc: 2,
            Sta: 0,
            Bal: 2,
            Agi: 2,
            Nat: 0,
            Str: 0,
            Pac: 1,
            Jum: 0,
        }
    },
    {
        // label: "Inverser Außenstürmer (Angreifen)",
        id: "r42",
        attributes: {

            Fin: 2,
            Fir: 2,
            Mar: 0,
            Dri: 2,
            Cor: 0,
            Pen: 0,
            Cro: 0,
            Fre: 0,
            Hea: 0,
            Pas: 1,
            Tck: 0,
            Tec: 2,
            L_Th: 0,
            Lon: 1,

            Agg: 0,
            Ant: 1,
            WOR: 0,
            Dec: 0,
            Fla: 1,
            Ldr: 0,
            Cnt: 0,
            Bra: 0,
            Cmp: 1,
            OTB: 2,
            Pos: 0,
            Tea: 0,
            Vis: 0,
            Det: 0,

            Acc: 2,
            Sta: 0,
            Bal: 2,
            Agi: 2,
            Nat: 0,
            Str: 0,
            Pac: 1,
            Jum: 0,
        }
    },
    {
        // label: "Inverser Flügelspieler (Unterstützen)",
        id: "r43",
        attributes: {

            Fin: 0,
            Fir: 1,
            Mar: 0,
            Dri: 2,
            Cor: 0,
            Pen: 0,
            Cro: 1,
            Fre: 0,
            Hea: 0,
            Pas: 2,
            Tck: 0,
            Tec: 2,
            L_Th: 0,
            Lon: 1,

            Agg: 0,
            Ant: 0,
            WOR: 1,
            Dec: 1,
            Fla: 0,
            Ldr: 0,
            Cnt: 0,
            Bra: 0,
            Cmp: 1,
            OTB: 2,
            Pos: 0,
            Tea: 0,
            Vis: 1,
            Det: 0,

            Acc: 2,
            Sta: 1,
            Bal: 0,
            Agi: 1,
            Nat: 0,
            Str: 0,
            Pac: 1,
            Jum: 0,
        }
    },
    {
        // label: "Inverser Flügelspieler (Angreifen)",
        id: "r44",
        attributes: {

            Fin: 0,
            Fir: 1,
            Mar: 0,
            Dri: 2,
            Cor: 0,
            Pen: 0,
            Cro: 1,
            Fre: 0,
            Hea: 0,
            Pas: 2,
            Tck: 0,
            Tec: 2,
            L_Th: 0,
            Lon: 1,

            Agg: 0,
            Ant: 1,
            WOR: 0,
            Dec: 1,
            Fla: 1,
            Ldr: 0,
            Cnt: 0,
            Bra: 0,
            Cmp: 1,
            OTB: 2,
            Pos: 0,
            Tea: 0,
            Vis: 1,
            Det: 0,

            Acc: 2,
            Sta: 0,
            Bal: 0,
            Agi: 2,
            Nat: 0,
            Str: 0,
            Pac: 1,
            Jum: 0,
        }
    },
    {
        // label: "Mezzala (Unterstützen)",
        id: "r45",
        attributes: {

            Fin: 0,
            Fir: 1,
            Mar: 0,
            Dri: 1,
            Cor: 0,
            Pen: 0,
            Cro: 0,
            Fre: 0,
            Hea: 0,
            Pas: 2,
            Tck: 1,
            Tec: 2,
            L_Th: 0,
            Lon: 1,

            Agg: 0,
            Ant: 1,
            WOR: 2,
            Dec: 2,
            Fla: 0,
            Ldr: 0,
            Cnt: 0,
            Bra: 0,
            Cmp: 1,
            OTB: 2,
            Pos: 0,
            Tea: 0,
            Vis: 1,
            Det: 0,

            Acc: 2,
            Sta: 1,
            Bal: 1,
            Agi: 0,
            Nat: 0,
            Str: 0,
            Pac: 0,
            Jum: 0,
        }
    },
    {
        // label: "Mezzala (Angreifen)",
        id: "r46",
        attributes: {

            Fin: 1,
            Fir: 1,
            Mar: 0,
            Dri: 2,
            Cor: 0,
            Pen: 0,
            Cro: 0,
            Fre: 0,
            Hea: 0,
            Pas: 2,
            Tck: 0,
            Tec: 2,
            L_Th: 0,
            Lon: 1,

            Agg: 0,
            Ant: 1,
            WOR: 2,
            Dec: 2,
            Fla: 1,
            Ldr: 0,
            Cnt: 0,
            Bra: 0,
            Cmp: 1,
            OTB: 2,
            Pos: 0,
            Tea: 0,
            Vis: 2,
            Det: 0,

            Acc: 2,
            Sta: 1,
            Bal: 1,
            Agi: 0,
            Nat: 0,
            Str: 0,
            Pac: 0,
            Jum: 0,
        }
    },
    {
        // label: "Offensiver Mittelfeldspieler (Unterstützen)",
        id: "r47",
        attributes: {

            Fin: 0,
            Fir: 2,
            Mar: 0,
            Dri: 1,
            Cor: 0,
            Pen: 0,
            Cro: 0,
            Fre: 0,
            Hea: 0,
            Pas: 2,
            Tck: 0,
            Tec: 2,
            L_Th: 0,
            Lon: 2,

            Agg: 0,
            Ant: 2,
            WOR: 0,
            Dec: 2,
            Fla: 2,
            Ldr: 0,
            Cnt: 0,
            Bra: 0,
            Cmp: 1,
            OTB: 2,
            Pos: 0,
            Tea: 0,
            Vis: 1,
            Det: 0,

            Acc: 0,
            Sta: 0,
            Bal: 0,
            Agi: 1,
            Nat: 0,
            Str: 0,
            Pac: 0,
            Jum: 0,
        }
    },
    {
        // label: "Offensiver Mittelfeldspieler (Angreifen)",
        id: "r48",
        attributes: {

            Fin: 1,
            Fir: 2,
            Mar: 0,
            Dri: 2,
            Cor: 0,
            Pen: 0,
            Cro: 0,
            Fre: 0,
            Hea: 0,
            Pas: 2,
            Tck: 0,
            Tec: 2,
            L_Th: 0,
            Lon: 2,

            Agg: 0,
            Ant: 2,
            WOR: 0,
            Dec: 2,
            Fla: 2,
            Ldr: 0,
            Cnt: 0,
            Bra: 0,
            Cmp: 1,
            OTB: 2,
            Pos: 0,
            Tea: 0,
            Vis: 1,
            Det: 0,

            Acc: 0,
            Sta: 0,
            Bal: 0,
            Agi: 1,
            Nat: 0,
            Str: 0,
            Pac: 0,
            Jum: 0,
        }
    },
    {
        // label: "Raumdeuter (Angreifen)",
        id: "r49",
        attributes: {

            Fin: 2,
            Fir: 1,
            Mar: 0,
            Dri: 0,
            Cor: 0,
            Pen: 0,
            Cro: 0,
            Fre: 0,
            Hea: 0,
            Pas: 0,
            Tck: 0,
            Tec: 1,
            L_Th: 0,
            Lon: 0,

            Agg: 0,
            Ant: 2,
            WOR: 1,
            Dec: 2,
            Fla: 0,
            Ldr: 0,
            Cnt: 2,
            Bra: 0,
            Cmp: 2,
            OTB: 2,
            Pos: 0,
            Tea: 0,
            Vis: 0,
            Det: 0,

            Acc: 1,
            Sta: 1,
            Bal: 2,
            Agi: 0,
            Nat: 0,
            Str: 0,
            Pac: 0,
            Jum: 0,
        }
    },
    {
        // label: "Regista (Unterstützen)",
        id: "r50",
        attributes: {

            Fin: 0,
            Fir: 2,
            Mar: 0,
            Dri: 1,
            Cor: 0,
            Pen: 0,
            Cro: 0,
            Fre: 0,
            Hea: 0,
            Pas: 2,
            Tck: 0,
            Tec: 2,
            L_Th: 0,
            Lon: 1,

            Agg: 0,
            Ant: 1,
            WOR: 0,
            Dec: 2,
            Fla: 2,
            Ldr: 0,
            Cnt: 0,
            Bra: 0,
            Cmp: 2,
            OTB: 2,
            Pos: 0,
            Tea: 2,
            Vis: 2,
            Det: 0,

            Acc: 0,
            Sta: 0,
            Bal: 1,
            Agi: 0,
            Nat: 0,
            Str: 0,
            Pac: 0,
            Jum: 0,
        }
    },
    {
        // label: "Schattenstürmer (Angreifen)",
        id: "r51",
        attributes: {

            Fin: 2,
            Fir: 2,
            Mar: 0,
            Dri: 2,
            Cor: 0,
            Pen: 0,
            Cro: 0,
            Fre: 0,
            Hea: 0,
            Pas: 1,
            Tck: 0,
            Tec: 1,
            L_Th: 0,
            Lon: 0,

            Agg: 0,
            Ant: 2,
            WOR: 1,
            Dec: 1,
            Fla: 0,
            Ldr: 0,
            Cnt: 1,
            Bra: 0,
            Cmp: 2,
            OTB: 2,
            Pos: 0,
            Tea: 0,
            Vis: 0,
            Det: 0,

            Acc: 2,
            Sta: 1,
            Bal: 1,
            Agi: 1,
            Nat: 0,
            Str: 0,
            Pac: 1,
            Jum: 0,
        }
    },
    {
        // label: "Segundo Volante (Unterstützen)",
        id: "r52",
        attributes: {

            Fin: 1,
            Fir: 1,
            Mar: 2,
            Dri: 0,
            Cor: 0,
            Pen: 0,
            Cro: 0,
            Fre: 0,
            Hea: 0,
            Pas: 2,
            Tck: 2,
            Tec: 0,
            L_Th: 0,
            Lon: 1,

            Agg: 0,
            Ant: 1,
            WOR: 2,
            Dec: 1,
            Fla: 0,
            Ldr: 0,
            Cnt: 1,
            Bra: 0,
            Cmp: 1,
            OTB: 2,
            Pos: 2,
            Tea: 0,
            Vis: 0,
            Det: 0,

            Acc: 1,
            Sta: 2,
            Bal: 1,
            Agi: 0,
            Nat: 0,
            Str: 1,
            Pac: 2,
            Jum: 0,
        }
    },
    {
        // label: "Segundo Volante (Angreifen)",
        id: "r53",
        attributes: {

            Fin: 2,
            Fir: 1,
            Mar: 1,
            Dri: 0,
            Cor: 0,
            Pen: 0,
            Cro: 0,
            Fre: 0,
            Hea: 0,
            Pas: 2,
            Tck: 2,
            Tec: 0,
            L_Th: 0,
            Lon: 2,

            Agg: 0,
            Ant: 2,
            WOR: 2,
            Dec: 1,
            Fla: 0,
            Ldr: 0,
            Cnt: 1,
            Bra: 0,
            Cmp: 1,
            OTB: 2,
            Pos: 2,
            Tea: 0,
            Vis: 0,
            Det: 0,

            Acc: 1,
            Sta: 2,
            Bal: 1,
            Agi: 0,
            Nat: 0,
            Str: 1,
            Pac: 2,
            Jum: 0,
        }
    },
    {
        // label: "Tiefer Sechser (Verteidigen)",
        id: "r54",
        attributes: {

            Fin: 0,
            Fir: 0,
            Mar: 2,
            Dri: 0,
            Cor: 0,
            Pen: 0,
            Cro: 0,
            Fre: 0,
            Hea: 1,
            Pas: 1,
            Tck: 2,
            Tec: 0,
            L_Th: 0,
            Lon: 0,

            Agg: 1,
            Ant: 2,
            WOR: 2,
            Dec: 1,
            Fla: 0,
            Ldr: 0,
            Cnt: 2,
            Bra: 1,
            Cmp: 1,
            OTB: 0,
            Pos: 2,
            Tea: 2,
            Vis: 0,
            Det: 0,

            Acc: 0,
            Sta: 2,
            Bal: 0,
            Agi: 0,
            Nat: 0,
            Str: 1,
            Pac: 0,
            Jum: 1,
        }
    },
    {
        // label: "Vertikaler Spielmacher (Unterstützen)",
        id: "r55",
        attributes: {

            Fin: 0,
            Fir: 2,
            Mar: 0,
            Dri: 1,
            Cor: 0,
            Pen: 0,
            Cro: 0,
            Fre: 0,
            Hea: 0,
            Pas: 2,
            Tck: 0,
            Tec: 2,
            L_Th: 0,
            Lon: 1,

            Agg: 0,
            Ant: 2,
            WOR: 2,
            Dec: 2,
            Fla: 0,
            Ldr: 0,
            Cnt: 1,
            Bra: 0,
            Cmp: 2,
            OTB: 2,
            Pos: 1,
            Tea: 2,
            Vis: 2,
            Det: 0,

            Acc: 2,
            Sta: 2,
            Bal: 1,
            Agi: 1,
            Nat: 0,
            Str: 0,
            Pac: 1,
            Jum: 0,
        }
    },
    {
        // label: "Vorgeschobener Spielmacher (Unterstützen)",
        id: "r56",
        attributes: {

            Fin: 0,
            Fir: 2,
            Mar: 0,
            Dri: 1,
            Cor: 0,
            Pen: 0,
            Cro: 0,
            Fre: 0,
            Hea: 0,
            Pas: 2,
            Tck: 0,
            Tec: 2,
            L_Th: 0,
            Lon: 0,

            Agg: 0,
            Ant: 1,
            WOR: 0,
            Dec: 2,
            Fla: 1,
            Ldr: 0,
            Cnt: 0,
            Bra: 0,
            Cmp: 2,
            OTB: 2,
            Pos: 0,
            Tea: 2,
            Vis: 2,
            Det: 0,

            Acc: 0,
            Sta: 0,
            Bal: 0,
            Agi: 1,
            Nat: 0,
            Str: 0,
            Pac: 0,
            Jum: 0,
        }
    },
    {
        // label: "Vorgeschobener Spielmacher (Angreifen)",
        id: "r57",
        attributes: {

            Fin: 0,
            Fir: 2,
            Mar: 0,
            Dri: 2,
            Cor: 0,
            Pen: 0,
            Cro: 0,
            Fre: 0,
            Hea: 0,
            Pas: 2,
            Tck: 0,
            Tec: 2,
            L_Th: 0,
            Lon: 0,

            Agg: 0,
            Ant: 1,
            WOR: 0,
            Dec: 2,
            Fla: 1,
            Ldr: 0,
            Cnt: 0,
            Bra: 0,
            Cmp: 2,
            OTB: 2,
            Pos: 0,
            Tea: 2,
            Vis: 2,
            Det: 0,

            Acc: 1,
            Sta: 0,
            Bal: 0,
            Agi: 1,
            Nat: 0,
            Str: 0,
            Pac: 0,
            Jum: 0,
        }
    },
    {
        // label: "Zentraler Mittelfeldspieler (Verteidigen)",
        id: "r58",
        attributes: {

            Fin: 0,
            Fir: 1,
            Mar: 1,
            Dri: 0,
            Cor: 0,
            Pen: 0,
            Cro: 0,
            Fre: 0,
            Hea: 0,
            Pas: 1,
            Tck: 2,
            Tec: 1,
            L_Th: 0,
            Lon: 0,

            Agg: 1,
            Ant: 1,
            WOR: 1,
            Dec: 2,
            Fla: 0,
            Ldr: 0,
            Cnt: 2,
            Bra: 0,
            Cmp: 1,
            OTB: 0,
            Pos: 2,
            Tea: 2,
            Vis: 0,
            Det: 0,

            Acc: 0,
            Sta: 1,
            Bal: 0,
            Agi: 0,
            Nat: 0,
            Str: 0,
            Pac: 0,
            Jum: 0,
        }
    },
    {
        // label: "Zentraler Mittelfeldspieler (Unterstützen)",
        id: "r59",
        attributes: {

            Fin: 0,
            Fir: 2,
            Mar: 0,
            Dri: 0,
            Cor: 0,
            Pen: 0,
            Cro: 0,
            Fre: 0,
            Hea: 0,
            Pas: 2,
            Tck: 2,
            Tec: 1,
            L_Th: 0,
            Lon: 0,

            Agg: 0,
            Ant: 1,
            WOR: 1,
            Dec: 2,
            Fla: 0,
            Ldr: 0,
            Cnt: 1,
            Bra: 0,
            Cmp: 1,
            OTB: 1,
            Pos: 0,
            Tea: 2,
            Vis: 1,
            Det: 0,

            Acc: 0,
            Sta: 1,
            Bal: 0,
            Agi: 0,
            Nat: 0,
            Str: 0,
            Pac: 0,
            Jum: 0,
        }
    },
    {
        // label: "Zentraler Mittelfeldspieler (Angreifen)",
        id: "r60",
        attributes: {

            Fin: 0,
            Fir: 2,
            Mar: 1,
            Dri: 0,
            Cor: 0,
            Pen: 0,
            Cro: 0,
            Fre: 0,
            Hea: 0,
            Pas: 2,
            Tck: 1,
            Tec: 1,
            L_Th: 0,
            Lon: 1,

            Agg: 0,
            Ant: 1,
            WOR: 1,
            Dec: 2,
            Fla: 0,
            Ldr: 0,
            Cnt: 0,
            Bra: 0,
            Cmp: 1,
            OTB: 2,
            Pos: 0,
            Tea: 1,
            Vis: 1,
            Det: 0,

            Acc: 1,
            Sta: 1,
            Bal: 0,
            Agi: 0,
            Nat: 0,
            Str: 0,
            Pac: 0,
            Jum: 0,
        }
    },
    {
        // label: "Zurückgezogener Spielmacher (Verteidigen)",
        id: "r61",
        attributes: {

            Fin: 0,
            Fir: 2,
            Mar: 0,
            Dri: 0,
            Cor: 0,
            Pen: 0,
            Cro: 0,
            Fre: 0,
            Hea: 0,
            Pas: 2,
            Tck: 1,
            Tec: 2,
            L_Th: 0,
            Lon: 0,

            Agg: 0,
            Ant: 1,
            WOR: 2,
            Dec: 2,
            Fla: 0,
            Ldr: 0,
            Cnt: 0,
            Bra: 0,
            Cmp: 2,
            OTB: 0,
            Pos: 1,
            Tea: 2,
            Vis: 2,
            Det: 0,

            Acc: 0,
            Sta: 0,
            Bal: 1,
            Agi: 0,
            Nat: 0,
            Str: 0,
            Pac: 0,
            Jum: 0,
        }
    },
    {
        // label: "Zurückgezogener Spielmacher (Unterstützen)",
        id: "r62",
        attributes: {

            Fin: 0,
            Fir: 2,
            Mar: 0,
            Dri: 0,
            Cor: 0,
            Pen: 0,
            Cro: 0,
            Fre: 0,
            Hea: 0,
            Pas: 2,
            Tck: 0,
            Tec: 2,
            L_Th: 0,
            Lon: 0,

            Agg: 0,
            Ant: 1,
            WOR: 1,
            Dec: 2,
            Fla: 0,
            Ldr: 0,
            Cnt: 0,
            Bra: 0,
            Cmp: 2,
            OTB: 1,
            Pos: 0,
            Tea: 2,
            Vis: 2,
            Det: 0,

            Acc: 0,
            Sta: 0,
            Bal: 1,
            Agi: 0,
            Nat: 0,
            Str: 0,
            Pac: 0,
            Jum: 0,
        }
    },

    // Striker
    {
        // label: "Falsche Neun (Unterstützen)",
        id: "r63",
        attributes: {

            Fin: 1,
            Fir: 2,
            Mar: 0,
            Dri: 2,
            Cor: 0,
            Pen: 0,
            Cro: 0,
            Fre: 0,
            Hea: 0,
            Pas: 2,
            Tck: 0,
            Tec: 2,
            L_Th: 0,
            Lon: 0,

            Agg: 0,
            Ant: 1,
            WOR: 0,
            Dec: 2,
            Fla: 1,
            Ldr: 0,
            Cnt: 0,
            Bra: 0,
            Cmp: 2,
            OTB: 2,
            Pos: 0,
            Tea: 1,
            Vis: 2,
            Det: 0,

            Acc: 2,
            Sta: 0,
            Bal: 1,
            Agi: 2,
            Nat: 0,
            Str: 0,
            Pac: 0,
            Jum: 0,
        }
    },
    {
        // label: "Hängende Spitze (Unterstützen)",
        id: "r64",
        attributes: {

            Fin: 1,
            Fir: 2,
            Mar: 0,
            Dri: 0,
            Cor: 0,
            Pen: 0,
            Cro: 0,
            Fre: 0,
            Hea: 0,
            Pas: 2,
            Tck: 0,
            Tec: 2,
            L_Th: 0,
            Lon: 0,

            Agg: 0,
            Ant: 1,
            WOR: 0,
            Dec: 2,
            Fla: 1,
            Ldr: 0,
            Cnt: 0,
            Bra: 0,
            Cmp: 2,
            OTB: 2,
            Pos: 0,
            Tea: 2,
            Vis: 1,
            Det: 0,

            Acc: 0,
            Sta: 0,
            Bal: 1,
            Agi: 0,
            Nat: 0,
            Str: 1,
            Pac: 0,
            Jum: 0,
        }
    },
    {
        // label: "Hängende Spitze (Angreifen)",
        id: "r65",
        attributes: {

            Fin: 1,
            Fir: 2,
            Mar: 0,
            Dri: 1,
            Cor: 0,
            Pen: 0,
            Cro: 0,
            Fre: 0,
            Hea: 0,
            Pas: 2,
            Tck: 0,
            Tec: 2,
            L_Th: 0,
            Lon: 0,

            Agg: 0,
            Ant: 1,
            WOR: 0,
            Dec: 2,
            Fla: 1,
            Ldr: 0,
            Cnt: 0,
            Bra: 0,
            Cmp: 2,
            OTB: 2,
            Pos: 0,
            Tea: 2,
            Vis: 1,
            Det: 0,

            Acc: 0,
            Sta: 0,
            Bal: 1,
            Agi: 0,
            Nat: 0,
            Str: 1,
            Pac: 0,
            Jum: 0,
        }
    },
    {
        // label: "Knipser (Angreifen)",
        id: "r66",
        attributes: {

            Fin: 2,
            Fir: 1,
            Mar: 0,
            Dri: 0,
            Cor: 0,
            Pen: 0,
            Cro: 0,
            Fre: 0,
            Hea: 1,
            Pas: 0,
            Tck: 0,
            Tec: 1,
            L_Th: 0,
            Lon: 0,

            Agg: 0,
            Ant: 2,
            WOR: 0,
            Dec: 1,
            Fla: 0,
            Ldr: 0,
            Cnt: 0,
            Bra: 0,
            Cmp: 2,
            OTB: 2,
            Pos: 0,
            Tea: 0,
            Vis: 0,
            Det: 0,

            Acc: 1,
            Sta: 0,
            Bal: 0,
            Agi: 0,
            Nat: 0,
            Str: 0,
            Pac: 0,
            Jum: 0,
        }
    },
    {
        // label: "Kompletter Stürmer (Unterstützen)",
        id: "r67",
        attributes: {

            Fin: 1,
            Fir: 2,
            Mar: 0,
            Dri: 2,
            Cor: 0,
            Pen: 0,
            Cro: 0,
            Fre: 0,
            Hea: 2,
            Pas: 2,
            Tck: 0,
            Tec: 2,
            L_Th: 0,
            Lon: 2,

            Agg: 0,
            Ant: 2,
            WOR: 1,
            Dec: 2,
            Fla: 0,
            Ldr: 0,
            Cnt: 0,
            Bra: 0,
            Cmp: 2,
            OTB: 2,
            Pos: 0,
            Tea: 1,
            Vis: 2,
            Det: 0,

            Acc: 2,
            Sta: 1,
            Bal: 1,
            Agi: 2,
            Nat: 0,
            Str: 2,
            Pac: 1,
            Jum: 1,
        }
    },
    {
        // label: "Kompletter Stürmer (Angreifen)",
        id: "r68",
        attributes: {

            Fin: 2,
            Fir: 2,
            Mar: 0,
            Dri: 2,
            Cor: 0,
            Pen: 0,
            Cro: 0,
            Fre: 0,
            Hea: 2,
            Pas: 1,
            Tck: 0,
            Tec: 2,
            L_Th: 0,
            Lon: 1,

            Agg: 0,
            Ant: 2,
            WOR: 1,
            Dec: 1,
            Fla: 0,
            Ldr: 0,
            Cnt: 0,
            Bra: 0,
            Cmp: 2,
            OTB: 2,
            Pos: 0,
            Tea: 1,
            Vis: 1,
            Det: 0,

            Acc: 2,
            Sta: 1,
            Bal: 1,
            Agi: 2,
            Nat: 0,
            Str: 2,
            Pac: 1,
            Jum: 1,
        }
    },
    {
        // label: "Pressender Stürmer (Verteidigen)",
        id: "r69",
        attributes: {

            Fin: 0,
            Fir: 1,
            Mar: 0,
            Dri: 0,
            Cor: 0,
            Pen: 0,
            Cro: 0,
            Fre: 0,
            Hea: 0,
            Pas: 0,
            Tck: 0,
            Tec: 0,
            L_Th: 0,
            Lon: 0,

            Agg: 2,
            Ant: 2,
            WOR: 2,
            Dec: 2,
            Fla: 0,
            Ldr: 0,
            Cnt: 1,
            Bra: 2,
            Cmp: 1,
            OTB: 0,
            Pos: 0,
            Tea: 2,
            Vis: 0,
            Det: 0,

            Acc: 2,
            Sta: 2,
            Bal: 1,
            Agi: 1,
            Nat: 0,
            Str: 1,
            Pac: 2,
            Jum: 0,
        }
    },
    {
        // label: "Pressender Stürmer (Unterstützen)",
        id: "r70",
        attributes: {

            Fin: 0,
            Fir: 1,
            Mar: 0,
            Dri: 0,
            Cor: 0,
            Pen: 0,
            Cro: 0,
            Fre: 0,
            Hea: 0,
            Pas: 1,
            Tck: 0,
            Tec: 0,
            L_Th: 0,
            Lon: 0,

            Agg: 2,
            Ant: 2,
            WOR: 2,
            Dec: 2,
            Fla: 0,
            Ldr: 0,
            Cnt: 1,
            Bra: 2,
            Cmp: 1,
            OTB: 1,
            Pos: 0,
            Tea: 2,
            Vis: 0,
            Det: 0,

            Acc: 2,
            Sta: 2,
            Bal: 1,
            Agi: 1,
            Nat: 0,
            Str: 1,
            Pac: 2,
            Jum: 0,
        }
    },
    {
        // label: "Pressender Stürmer (Angreifen)",
        id: "r71",
        attributes: {

            Fin: 1,
            Fir: 1,
            Mar: 0,
            Dri: 0,
            Cor: 0,
            Pen: 0,
            Cro: 0,
            Fre: 0,
            Hea: 0,
            Pas: 0,
            Tck: 0,
            Tec: 0,
            L_Th: 0,
            Lon: 0,

            Agg: 2,
            Ant: 2,
            WOR: 2,
            Dec: 1,
            Fla: 0,
            Ldr: 0,
            Cnt: 1,
            Bra: 2,
            Cmp: 1,
            OTB: 2,
            Pos: 0,
            Tea: 2,
            Vis: 0,
            Det: 0,

            Acc: 2,
            Sta: 2,
            Bal: 1,
            Agi: 1,
            Nat: 0,
            Str: 1,
            Pac: 2,
            Jum: 0,
        }
    },
    {
        // label: "Stoßstürmer (Angreifen)",
        id: "r72",
        attributes: {

            Fin: 2,
            Fir: 2,
            Mar: 0,
            Dri: 2,
            Cor: 0,
            Pen: 0,
            Cro: 0,
            Fre: 0,
            Hea: 0,
            Pas: 1,
            Tck: 0,
            Tec: 2,
            L_Th: 0,
            Lon: 0,

            Agg: 0,
            Ant: 1,
            WOR: 1,
            Dec: 1,
            Fla: 0,
            Ldr: 0,
            Cnt: 0,
            Bra: 0,
            Cmp: 2,
            OTB: 2,
            Pos: 0,
            Tea: 0,
            Vis: 0,
            Det: 0,

            Acc: 2,
            Sta: 1,
            Bal: 1,
            Agi: 1,
            Nat: 0,
            Str: 0,
            Pac: 1,
            Jum: 0,
        }
    },
    {
        // label: "Trequartista (Angreifen)",
        id: "r73",
        attributes: {

            Fin: 1,
            Fir: 2,
            Mar: 0,
            Dri: 2,
            Cor: 0,
            Pen: 0,
            Cro: 0,
            Fre: 0,
            Hea: 0,
            Pas: 2,
            Tck: 0,
            Tec: 2,
            L_Th: 0,
            Lon: 0,

            Agg: 0,
            Ant: 1,
            WOR: 0,
            Dec: 2,
            Fla: 2,
            Ldr: 0,
            Cnt: 0,
            Bra: 0,
            Cmp: 2,
            OTB: 2,
            Pos: 0,
            Tea: 0,
            Vis: 2,
            Det: 0,

            Acc: 2,
            Sta: 0,
            Bal: 1,
            Agi: 1,
            Nat: 0,
            Str: 0,
            Pac: 0,
            Jum: 0,
        }
    },
    {
        // label: "Zielspieler (Unterstützen)",
        id: "r74",
        attributes: {

            Fin: 1,
            Fir: 1,
            Mar: 0,
            Dri: 0,
            Cor: 0,
            Pen: 0,
            Cro: 0,
            Fre: 0,
            Hea: 2,
            Pas: 0,
            Tck: 0,
            Tec: 0,
            L_Th: 0,
            Lon: 0,

            Agg: 1,
            Ant: 1,
            WOR: 0,
            Dec: 1,
            Fla: 0,
            Ldr: 0,
            Cnt: 0,
            Bra: 2,
            Cmp: 1,
            OTB: 1,
            Pos: 0,
            Tea: 2,
            Vis: 0,
            Det: 0,

            Acc: 0,
            Sta: 0,
            Bal: 2,
            Agi: 0,
            Nat: 0,
            Str: 2,
            Pac: 0,
            Jum: 2,
        }
    },
    {
        // label: "Zielspieler (Angreifen)",
        id: "r75",
        attributes: {

            Fin: 2,
            Fir: 1,
            Mar: 0,
            Dri: 0,
            Cor: 0,
            Pen: 0,
            Cro: 0,
            Fre: 0,
            Hea: 2,
            Pas: 0,
            Tck: 0,
            Tec: 0,
            L_Th: 0,
            Lon: 0,

            Agg: 1,
            Ant: 1,
            WOR: 0,
            Dec: 1,
            Fla: 0,
            Ldr: 0,
            Cnt: 0,
            Bra: 2,
            Cmp: 2,
            OTB: 2,
            Pos: 0,
            Tea: 1,
            Vis: 0,
            Det: 0,

            Acc: 0,
            Sta: 0,
            Bal: 2,
            Agi: 0,
            Nat: 0,
            Str: 2,
            Pac: 0,
            Jum: 2,
        }
    },
    {
        // label: "Defensiver Mittelfeldspieler (Verteidigen)",
        id: "r76",
        attributes: {

            Fin: 0,
            Fir: 0,
            Mar: 1,
            Dri: 0,
            Cor: 0,
            Pen: 0,
            Cro: 0,
            Fre: 0,
            Hea: 0,
            Pas: 1,
            Tck: 2,
            Tec: 0,
            L_Th: 0,
            Lon: 0,

            Agg: 1,
            Ant: 2,
            WOR: 2,
            Dec: 1,
            Fla: 0,
            Ldr: 0,
            Cnt: 2,
            Bra: 0,
            Cmp: 1,
            OTB: 0,
            Pos: 2,
            Tea: 2,
            Vis: 0,
            Det: 0,

            Acc: 0,
            Sta: 2,
            Bal: 0,
            Agi: 0,
            Nat: 0,
            Str: 1,
            Pac: 0,
            Jum: 0,
        }
    },
    {
        // label: "Defensiver Mittelfeldspieler (Unterstützen)",
        id: "r77",
        attributes: {

            Fin: 0,
            Fir: 1,
            Mar: 1,
            Dri: 0,
            Cor: 0,
            Pen: 0,
            Cro: 0,
            Fre: 0,
            Hea: 0,
            Pas: 1,
            Tck: 2,
            Tec: 0,
            L_Th: 0,
            Lon: 0,

            Agg: 1,
            Ant: 2,
            WOR: 2,
            Dec: 1,
            Fla: 0,
            Ldr: 0,
            Cnt: 2,
            Bra: 0,
            Cmp: 1,
            OTB: 0,
            Pos: 2,
            Tea: 2,
            Vis: 0,
            Det: 0,

            Acc: 0,
            Sta: 2,
            Bal: 0,
            Agi: 0,
            Nat: 0,
            Str: 1,
            Pac: 0,
            Jum: 0,
        }
    },
];

window.roles = roles;